language: cpp
sudo: false   # Use the new container infrastructure

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - cmake-data
      - cmake
env:
  - COMPILER=g++-5 STDLIB=libc++
install:
  - git submodule update --init --recursive
  # Boost
  - cd contrib/boost
  - ./bootstrap.sh
  - ./b2 headers
before_script:
  - cd ../..
  - rm -rf build/
  - mkdir build
  - cd build
script:
  - cmake -DCMAKE_CXX_COMPILER=${COMPILER} .
  - cmake --build .
  - make test
